# wrangler.toml
name = 'remaster-kingdom-worker'
main = "src/_worker.js"
keep_vars = true
compatibility_date = "2025-12-15"

[[kv_namespaces]]
binding = "KV"
id = "d9bbc39747e20eabbc0b198b2e5e7cf2"

[vars]
PAGES = "https://edt-pages.github.io"

