# wrangler.toml
name = 'remaster-kingdom-worker'
main = "src/_worker.js"
keep_vars = true
compatibility_date = "2025-12-15"

[[kv_namespaces]]
binding = "KV"
id = "c43788e0-ca23-491c-b05b-0e7a1ef7bfdf"

[vars]
PAGES = "https://edt-pages.github.io"


